// =============================================================================
// OTG Safety System — Canonical Service Worker
// =============================================================================
// This is a committed, versioned file — not generated by the Factory.
// Update SW_VERSION when you deploy new app files so old caches are cleared.
// config.json is cached with a network-first strategy so workers always get
// the freshest config when online, but the app still works fully offline.
// =============================================================================

const SW_VERSION = '1.0.0';
const CACHE_NAME = `otg-safety-${SW_VERSION}`;

// Assets that MUST be cached at install time for offline-first operation.
// config.json is deliberately included — the app cannot start without it.
const CRITICAL_ASSETS = [
  './',
  './index.html',
  './sw.js',
  './manifest.json',
  './icon.png',
  './config.json',
  'https://cdnjs.cloudflare.com/ajax/libs/tone/14.7.77/Tone.js',
  'https://cdn.tailwindcss.com'
];

// =============================================================================
// INSTALL: Cache all critical assets
// =============================================================================
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(async cache => {
        console.log('[SW] Installing — pre-caching critical assets...');
        for (const url of CRITICAL_ASSETS) {
          try {
            const response = await fetch(url, {
              mode: url.startsWith('http') ? 'no-cors' : 'cors',
              redirect: 'follow'
            });
            await cache.put(url, response);
          } catch (err) {
            // Non-fatal: asset unavailable at install time (e.g. first load while
            // offline). The fetch handler will try again at runtime.
            console.warn('[SW] Could not pre-cache:', url, err.message);
          }
        }
        console.log('[SW] Pre-cache complete.');
      })
      .then(() => self.skipWaiting())
      .catch(err => console.error('[SW] Install failed:', err))
  );
});

// =============================================================================
// ACTIVATE: Delete caches from previous SW versions
// =============================================================================
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys
          .filter(key => {
            // Purge old versioned app caches, but keep:
            //   CACHE_NAME        — current version (obviously)
            //   'otg-manifest'    — long-lived store for dynamic org manifest;
            //                       written by the main app's _injectDynamicManifest()
            //                       and read by this SW's manifest intercept handler.
            //                       Must survive SW version bumps or the org-branded
            //                       manifest would be lost on every update.
            return key !== CACHE_NAME && key !== 'otg-manifest';
          })
          .map(key => {
            console.log('[SW] Deleting old cache:', key);
            return caches.delete(key);
          })
      ))
      .then(() => self.clients.claim())
  );
});

// =============================================================================
// FETCH: Differentiated caching strategy
//
// manifest.json → Dynamic build from cached config.json
//   Rationale: The canonical manifest.json is generic ("OTG Safety"). Once
//   config.json is cached the SW can synthesise an org-branded manifest on
//   every request, so the installed PWA shows the correct org name.
//   Falls back to the static cached manifest if config.json is not yet cached
//   (first install before config was fetched).
//
// config.json  → Network-first, cache fallback
//   Rationale: Config changes must propagate promptly when online. Cached copy
//   ensures offline operation. Version mismatch detection is handled in the
//   main app, not the SW.
//
// All other GET requests → Cache-first, network fallback
//   Rationale: App shell assets rarely change; offline performance is critical.
// =============================================================================

/**
 * Builds a Web App Manifest object from a parsed config.json object.
 * Used by the fetch handler to synthesise org-branded manifest responses.
 * Kept as a plain function (not async) so it can be called synchronously
 * inside a Promise chain.
 */
function _buildManifestFromConfig(cfg) {
  const orgName = (cfg && cfg.orgName)  ? cfg.orgName  : 'OTG';
  const appName = (cfg && cfg.appName)  ? cfg.appName  : orgName;
  const primary = (cfg && cfg.theme && cfg.theme.primary) ? cfg.theme.primary : '#1e3a8a';
  const logo    = (cfg && cfg.logoUrl)  ? cfg.logoUrl  : './icon.png';
  return {
    name:             `${orgName} Safety`,
    short_name:       appName,
    description:      'Lone worker safety monitoring app',
    start_url:        './index.html',
    display:          'standalone',
    background_color: primary,
    theme_color:      primary,
    orientation:      'portrait',
    icons: [
      { src: logo, sizes: '192x192', type: 'image/png' },
      { src: logo, sizes: '512x512', type: 'image/png', purpose: 'any maskable' }
    ]
  };
}
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  const isManifest = url.pathname.endsWith('/manifest.json');
  const isConfig   = url.pathname.endsWith('/config.json');

  // ── manifest.json: synthesise org-branded response from cached config ──────
  if (isManifest) {
    event.respondWith(
      (async () => {
        try {
          // Derive the config.json URL from the manifest request URL so relative
          // paths resolve correctly regardless of deployment sub-directory.
          const configUrl = event.request.url.replace(/manifest\.json(\?.*)?$/, 'config.json');
          const cachedConfig = await caches.match(configUrl);
          if (cachedConfig) {
            const cfg = await cachedConfig.json();
            if (cfg && !cfg._error) {
              const manifest = _buildManifestFromConfig(cfg);
              console.log(`[SW] Serving dynamic manifest for "${manifest.name}"`);
              return new Response(JSON.stringify(manifest, null, 2), {
                status:  200,
                headers: { 'Content-Type': 'application/manifest+json' }
              });
            }
          }
        } catch (e) {
          console.warn('[SW] Dynamic manifest build failed, falling back to static:', e);
        }
        // Fallback 1: static manifest.json from any cache
        const cached = await caches.match(event.request);
        if (cached) return cached;
        // Fallback 2: network
        return fetch(event.request).catch(() =>
          new Response('{}', { status: 503, headers: { 'Content-Type': 'application/json' } })
        );
      })()
    );
    return;
  }

  if (isConfig) {
    // Network-first for config.json
    event.respondWith(
      fetch(event.request)
        .then(networkResponse => {
          if (networkResponse && (networkResponse.status === 200 || networkResponse.status === 0)) {
            // Clone BEFORE returning to browser — body can only be consumed once
            const responseToCache = networkResponse.clone();
            caches.open(CACHE_NAME).then(cache => cache.put(event.request, responseToCache));
          }
          return networkResponse;
        })
        .catch(() => {
          // Network failed — serve cached config (offline operation)
          return caches.match(event.request).then(cached => {
            if (cached) {
              console.log('[SW] Offline: serving cached config.json');
              return cached;
            }
            // No cache — return error response; boot screen handles this gracefully
            return new Response(JSON.stringify({ _error: 'config_unavailable_offline' }), {
              status: 503,
              headers: { 'Content-Type': 'application/json' }
            });
          });
        })
    );
    return;
  }

  // Cache-first for all other assets
  event.respondWith(
    caches.match(event.request).then(cached => {
      if (cached) return cached;

      return fetch(event.request)
        .then(networkResponse => {
          if (networkResponse &&
              (networkResponse.status === 200 || networkResponse.status === 0)) {
            // Clone BEFORE returning to browser (body-already-used guard)
            const responseToCache = networkResponse.clone();
            caches.open(CACHE_NAME).then(cache => cache.put(event.request, responseToCache));
          }
          return networkResponse;
        })
        .catch(() => {
          // Network failed, nothing cached — return minimal offline stub
          return caches.match('./') ||
            new Response('Offline', { status: 503, headers: { 'Content-Type': 'text/plain' } });
        });
    })
  );
});

// =============================================================================
// MESSAGES: Handle skip-waiting from main app
// =============================================================================
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // event.waitUntil() keeps the SW alive until skipWaiting() resolves,
    // preventing "message channel closed before a response was received".
    event.waitUntil(self.skipWaiting());
  }
});
